# DAAS API
app:
# Generate DAAS Token
  daastoken:
    url: https://api-np.anthem.com/v1/oauth/accesstoken
    apikey: UJAErFMgg6nduZB5VAGJoYR9y4IEeKVc
    auth: Basic MWRhYTA2N2QxY2RlNDdjOTk0MGQ5MzcwODgyMWQzZmY6N2EzNDY3Mjc0YTU3MTE5ZDA4NmE2ZTM4NzNhMzhlYmIzNTZlMDAwNmRiM2VlMWIzY2YyZDNjMGYwZGI5M2RlMA==
    granttype: client_credentials
    scope: public
    clientid: 1bl7e8u5tfhqou57itfe2ghbup
    clientsecret: 1dna733ms84s70hdlso98h9ak5svm4ue6csk6gq53nlhtubp42oc
    refreshTokenFlag: false
    refresh-time: 5

  daasapi:
    url: https://api-np.anthem.com/
    xapikey: UJAErFMgg6nduZB5VAGJoYR9y4IEeKVc
    apikey: UJAErFMgg6nduZB5VAGJoYR9y4IEeKVc
    prefix: v1/pocep
    reference-product: ${app.daasapi.url}${app.daasapi.prefix}/reference/products
    provider-product: ${app.daasapi.url}${app.daasapi.prefix}/providers/product
    mixer-hierarchy: ${app.daasapi.url}${app.daasapi.prefix}/mixer/hierarchy
    mixer-product: ${app.daasapi.url}${app.daasapi.prefix}/mixers/products